var dataset = [
 {
   "ID": 1,
   "IG username": "hasmik_avetisyan",
   "Gender": "Female",
   "Occasion": "Graduation",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Closing an amazing chapter of my life 🎓💛 #graduation",
   "Language": "Eng",
   "Length": 7,
   "# of emojis": 2,
   "# of hashtags": 1,
   "Likes": 274,
   "Comments": 16,
   "Followers": 1256
 },
 {
   "ID": 2,
   "IG username": "mantaaash",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Enjoying Armenian October to the fullest! #LetItBe 📸: @mar.h_ ☀️",
   "Language": "Eng",
   "Length": 6,
   "# of emojis": 2,
   "# of hashtags": 1,
   "Likes": 297,
   "Comments": 40,
   "Followers": 1135
 },
 {
   "ID": 3,
   "IG username": "michelle__shaboyan",
   "Gender": "Female",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Intelligent mardik🤓🤓❤️❤️from Italy and India!!!",
   "Language": "Eng",
   "Length": 6,
   "# of emojis": 4,
   "# of hashtags": 0,
   "Likes": 83,
   "Comments": 7,
   "Followers": 660
 },
 {
   "ID": 4,
   "IG username": "whim_mind",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "#ggj2020",
   "Language": "Eng",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 1,
   "Likes": 16,
   "Comments": 1,
   "Followers": 44
 },
 {
   "ID": 5,
   "IG username": "fulbwriter",
   "Gender": "Female",
   "Occasion": "Landscape",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Oh hay there\n.\n.\n.\n[Image description: snowy trees surround an Armenian flag overlooking Yerevan.]\n.\n.\n.\n#yerevan #armenia #dzyun",
   "Language": "Eng",
   "Length": 13,
   "# of emojis": 0,
   "# of hashtags": 3,
   "Likes": 31,
   "Comments": 0,
   "Followers": 107
 },
 {
   "ID": 6,
   "IG username": "shahane_movsisyan",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "none",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 67,
   "Comments": 3,
   "Followers": 424
 },
 {
   "ID": 7,
   "IG username": "_.salvi_nalbandian._22",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "Save paper,don’t do homework🗒😂",
   "Language": "Eng",
   "Length": 5,
   "# of emojis": 2,
   "# of hashtags": 0,
   "Likes": 57,
   "Comments": 6,
   "Followers": 275
 },
 {
   "ID": 8,
   "IG username": "samvel_kirakosyan",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "none",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 58,
   "Comments": 1,
   "Followers": 548
 },
 {
   "ID": 9,
   "IG username": "shushghandilyan",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "I trust the next chapter ‘cause I know the author 💫",
   "Language": "Eng",
   "Length": 10,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 147,
   "Comments": 2,
   "Followers": 1422
 },
 {
   "ID": 10,
   "IG username": "_arturov1ch_",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "👑 #47rf777",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 1,
   "# of hashtags": 1,
   "Likes": 102,
   "Comments": 11,
   "Followers": 859
 },
 {
   "ID": 11,
   "IG username": "_helenkh",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "stand back, competing with no one but myself",
   "Language": "Eng",
   "Length": 8,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 301,
   "Comments": 19,
   "Followers": 1159
 },
 {
   "ID": 12,
   "IG username": "tigran_13",
   "Gender": "Male",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "none",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 81,
   "Comments": 1,
   "Followers": 159
 },
 {
   "ID": 13,
   "IG username": "yeva_kay",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Wish dream,do it 💫",
   "Language": "Eng",
   "Length": 4,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 84,
   "Comments": 9,
   "Followers": 336
 },
 {
   "ID": 14,
   "IG username": "diana__mkrtchyan",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Keep your head high, keep your chin up, and most importantly, keep smiling, because life’s a beautiful thing and there’s so much to smile about. 💫😇",
   "Language": "Eng",
   "Length": 27,
   "# of emojis": 2,
   "# of hashtags": 0,
   "Likes": 143,
   "Comments": 4,
   "Followers": 513
 },
 {
   "ID": 15,
   "IG username": "_stranger_who_takes_care__",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "“It’s weird not to be weird” ~John Lennon~ credits to @nellygasparyaan 💜",
   "Language": "Eng",
   "Length": 12,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 165,
   "Comments": 24,
   "Followers": 417
 },
 {
   "ID": 16,
   "IG username": "xchton ",
   "Gender": "Male",
   "Occasion": "Landscape",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "#w124 #230E #mercedesbenz#mercedes #eklasse",
   "Language": "Eng",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 5,
   "Likes": 29,
   "Comments": 0,
   "Followers": 320
 },
 {
   "ID": 17,
   "IG username": "arpine__gharibyan ",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "😎",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 122,
   "Comments": 0,
   "Followers": 332
 },
 {
   "ID": 18,
   "IG username": "___daisymoon ",
   "Gender": "Female",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Red Never Fails Me 💋 Winterball ❄️ #red #cherry #winterball #winter #december #wine #aesthetic #party #night #nightout #look #lifestyle #college #redlips #photooftheday #daisy #daisymoon #vsco #youth #wild #passion #blog #style #follow #bestoftheday #fun #instagood #redhair #gingerhair #aesthetic #ponytail",
   "Language": "Eng",
   "Length": 5,
   "# of emojis": 2,
   "# of hashtags": 31,
   "Likes": 256,
   "Comments": 16,
   "Followers": 742
 },
 {
   "ID": 19,
   "IG username": "lshirvanyanl ",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "🤞🏾",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 215,
   "Comments": 6,
   "Followers": 2235
 },
 {
   "ID": 20,
   "IG username": "dayana.amirkhanyan ",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "reshman seminar 1️⃣ - S Fall 2019 ✨",
   "Language": "Eng",
   "Length": 5,
   "# of emojis": 2,
   "# of hashtags": 0,
   "Likes": 181,
   "Comments": 0,
   "Followers": 1996
 },
 {
   "ID": 21,
   "IG username": "alainmazmanian98\n",
   "Gender": "Male",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "I can't express how grateful and honored I am to have been part of Creative Evening 2.0. I love entertaining people and it was a dream for me to do Stand-up at AUA. #CreativeEvening2.0 #AUA",
   "Language": "Eng",
   "Length": 33,
   "# of emojis": 0,
   "# of hashtags": 2,
   "Likes": 61,
   "Comments": 0,
   "Followers": 315
 },
 {
   "ID": 22,
   "IG username": "varvara_ohan",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "One more educational day in AUA... 🤩 Projects with AUA are passing lot of interesting and effectively... 😍Thanks AUA for cooperation with our educational complex “Mkhitar Sebastatsi” 😊❤️",
   "Language": "Eng",
   "Length": 25,
   "# of emojis": 4,
   "# of hashtags": 0,
   "Likes": 45,
   "Comments": 1,
   "Followers": 368
 },
 {
   "ID": 23,
   "IG username": "arm.gr",
   "Gender": "Male",
   "Occasion": "Lanscape",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 52,
   "Comments": 0,
   "Followers": 442
 },
 {
   "ID": 24,
   "IG username": "hayastan.ir",
   "Gender": "Male",
   "Occasion": "Lanscape",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "اگر میخواهید تو یه کشور ارزان، نزدیک و راحت یه مدرک معتبر از دانشگاه امریکایی داشته باشید. دانشگاه امریکایی یروان میتونه گزینه خوبی باشه\n\n#دانشگاه #دانشگاه_امریکایی #دانشگاه_امریکا #ادامه_تحصیل #ادامه_تحصیل_در_خارج #ادامه_تحصیل_آمریکا #یروان #ارمنستان #ایروان #ایروان_گردی #هایاستان",
   "Language": "Other",
   "Length": 35,
   "# of emojis": 0,
   "# of hashtags": 11,
   "Likes": 26,
   "Comments": 1,
   "Followers": 8745
 },
 {
   "ID": 25,
   "IG username": "Lifestyle",
   "Gender": "Female",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "YES, ARMENIAN WOMEN CAN !!! because they are the foundation and the future.",
   "Language": "Eng",
   "Length": 12,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 10300,
   "Comments": 21,
   "Followers": 156000
 },
 {
   "ID": 26,
   "IG username": "scappatodicasa17",
   "Gender": "Male",
   "Occasion": "Event",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "📍Day 9️⃣4️⃣ 🇦🇲\n.\nÈ proprio vero che quando viaggi può SUCCEDERE DI TUTTO.\nIo, ad esempio, son finito all’UNIVERSITÀ.\nIn cosa potrò mai laurearmi?\n———————————————————————————\n🇬🇧📍Day 9️⃣4️⃣ 🇦🇲\n.\nIt’s true that when you travel, EVERYTHING CAN HAPPENS.\nToday, for example, I went to UNIVERSITY.\nWhat can I ever graduate in?",
   "Language": "Other",
   "Length": 47,
   "# of emojis": 9,
   "# of hashtags": 30,
   "Likes": 100,
   "Comments": 8,
   "Followers": 1045
 },
 {
   "ID": 27,
   "IG username": "",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "A5wanii❤️",
   "Language": "Other",
   "Length": 1,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 1021,
   "Comments": 32,
   "Followers": 10200
 },
 {
   "ID": 28,
   "IG username": "",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Enjoying Armenian October to the fullest! #LetItBe 📸: @mar.h_ ☀️",
   "Language": "Eng",
   "Length": 6,
   "# of emojis": 1,
   "# of hashtags": 1,
   "Likes": 297,
   "Comments": 40,
   "Followers": 1134
 },
 {
   "ID": 29,
   "IG username": "zaruhibatoyan",
   "Gender": "Female",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Այսօր ներկա գտնվեցի «Փոխի՛ր աշխարհը» իրազեկման արշավի շրջանակում հայտարարված դպրոցական շարադրությունների մրցույթի մրցանակաբաշխությանը։ ✅ \"Մեր նպատակը բոլոր երեխաների կրթությունը հանրակրթական դպրոցներում կազմակերպելն է\"։",
   "Language": "Arm",
   "Length": 24,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 108,
   "Comments": 0,
   "Followers": 1396
 },
 {
   "ID": 30,
   "IG username": "tigran__13",
   "Gender": "Male",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 81,
   "Comments": 1,
   "Followers": 159
 },
 {
   "ID": 31,
   "IG username": "__zakar__",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "13w",
   "Language": "Eng",
   "Length": 4,
   "# of emojis": 0,
   "# of hashtags": 1,
   "Likes": 122,
   "Comments": 10,
   "Followers": 427
 },
 {
   "ID": 32,
   "IG username": "nane.avetisyan\n",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "🔹",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 94,
   "Comments": 3,
   "Followers": 184
 },
 {
   "ID": 33,
   "IG username": "fast_foundation\n",
   "Gender": "Female",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Thanks @aua_insta for such a warm welcome!\n\n#IndonesiArmenia 🇮🇩🇦🇲",
   "Language": "Eng",
   "Length": 6,
   "# of emojis": 0,
   "# of hashtags": 1,
   "Likes": 37,
   "Comments": 0,
   "Followers": 1474
 },
 {
   "ID": 34,
   "IG username": "avetisyan_88\n\n",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 121,
   "Comments": 2,
   "Followers": 250
 },
 {
   "ID": 35,
   "IG username": "_anikhachatryan_",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "💛",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 59,
   "Comments": 2,
   "Followers": 378
 },
 {
   "ID": 36,
   "IG username": "_.salvi_nalbandian._22\n",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "Save paper,don’t do homework🗒😂",
   "Language": "Eng",
   "Length": 5,
   "# of emojis": 2,
   "# of hashtags": 0,
   "Likes": 57,
   "Comments": 6,
   "Followers": 278
 },
 {
   "ID": 37,
   "IG username": "uniqcaptions\n",
   "Gender": "Female",
   "Occasion": "Event",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "🤩 Yesterday, we graduated from the EPIC Incubation program! It was an incredible journey filled with advice, endless support, and a lot of pizza 🍕\nThanks to the EPIC team for making it epic!\n- Team uniQ\n\nP. S. If you find yourself, comment 🧡\n#DemoDay #pitch #epic #selfie #team #teamwork",
   "Language": "Eng",
   "Length": 46,
   "# of emojis": 3,
   "# of hashtags": 6,
   "Likes": 81,
   "Comments": 12,
   "Followers": 173
 },
 {
   "ID": 38,
   "IG username": "nairi____",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "#PSIA",
   "Language": "Eng",
   "Length": 1,
   "# of emojis": 0,
   "# of hashtags": 1,
   "Likes": 152,
   "Comments": 3,
   "Followers": 470
 },
 {
   "ID": 39,
   "IG username": "zalyanm",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "GM ☀️",
   "Language": "Eng",
   "Length": 1,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 159,
   "Comments": 18,
   "Followers": 594
 },
 {
   "ID": 40,
   "IG username": "nar3k\n",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Շատ եմ հավանել էս նկարը։ Քանի որ հավանողներն ու հարցնողները քիչ չէին, կասեմ։\n⠀\nՍաղ նկարներս նկարածա հեռախոսովս:\n⠀\nՍիրուն Ձեռագիրը էդ մարդու շնորհքնա, ոչ թե լավ գրչի:\nՆույննա որ մեկը համով ճաշեր սարքի,\nդու մտածես որ կաստրյուլկեքն են լավը))))\n⠀\nԷդ հեչ: Ինձ ավելի շատ հետաքրքիրա ոնց են մարդիկ Այֆոն 11ով Պն Նոկիաի նկարներ ստանում,այ էդա տաղանդը🤔😂\n⠀\n📷 Instagram.com/Nar3k\n📷 Samsung Galaxy S7 Edge",
   "Language": "Arm",
   "Length": 17,
   "# of emojis": 4,
   "# of hashtags": 0,
   "Likes": 420,
   "Comments": 12,
   "Followers": 1781
 },
 {
   "ID": 41,
   "IG username": "wildyyy__",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "улыбаемся светлому будущему",
   "Language": "Rus",
   "Length": 3,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 312,
   "Comments": 14,
   "Followers": 1281
 },
 {
   "ID": 42,
   "IG username": "yuro_m",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "#🖐🏻",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 1,
   "# of hashtags": 1,
   "Likes": 145,
   "Comments": 1,
   "Followers": 346
 },
 {
   "ID": 43,
   "IG username": "_arpina",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "Keep your hands as clean as your heart is, both enough to keep COVID-19 away. But on a serious note... I hope you are all fine and well♥️ night )",
   "Language": "Eng",
   "Length": 29,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 149,
   "Comments": 7,
   "Followers": 816
 },
 {
   "ID": 44,
   "IG username": "marymkrtchyan_",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Find someone who will look at you the same way as I look at my coffee ✨",
   "Language": "Eng",
   "Length": 16,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 47,
   "Comments": 4,
   "Followers": 231
 },
 {
   "ID": 45,
   "IG username": "dawid_arakelyan",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "z ciemnych głębin",
   "Language": "Other",
   "Length": 3,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 238,
   "Comments": 0,
   "Followers": 3771
 },
 {
   "ID": 46,
   "IG username": "rv______0_____rv",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "They say tongue is the strongest muscle of the body. Wanna fight?😋👊 #love.#instagood.#photooftheday.#fashion.#beautiful.#happy#cute.#tbt.#yerevancity",
   "Language": "Eng",
   "Length": 12,
   "# of emojis": 2,
   "# of hashtags": 9,
   "Likes": 34,
   "Comments": 2,
   "Followers": 186
 },
 {
   "ID": 47,
   "IG username": "lily__2904",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "I'm still learning to love myself",
   "Language": "Eng",
   "Length": 6,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 178,
   "Comments": 12,
   "Followers": 812
 },
 {
   "ID": 48,
   "IG username": "grigor_ghazaryan",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "😎",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 108,
   "Comments": 2,
   "Followers": 346
 },
 {
   "ID": 49,
   "IG username": "narekharutyunian_",
   "Gender": "Male",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "💎🇬🇧🗽 @aua_insta @aua_sc #aua #library #openhouse",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 3,
   "# of hashtags": 3,
   "Likes": 82,
   "Comments": 7,
   "Followers": 727
 },
 {
   "ID": 50,
   "IG username": "marymargaryan_",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "there's two of us, always, you just see one at a time. *two fish swimming in opposite directions*",
   "Language": "Eng",
   "Length": 18,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 130,
   "Comments": 33,
   "Followers": 593
 },
 {
   "ID": 51,
   "IG username": "sevakx",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "yes",
   "Caption": "Էն որ ✌️ արած մանրիիիիից տանում ես ու չես կարում կադրի մեջ հասցնես տեղ. Սկսենք #-ներ դնել նկարների տակ #դիպլոմային #capstone #simulation #game",
   "Language": "Arm",
   "Length": 20,
   "# of emojis": 1,
   "# of hashtags": 4,
   "Likes": 50,
   "Comments": 0,
   "Followers": 252
 },
 {
   "ID": 52,
   "IG username": "arthurasatryan__",
   "Gender": "Male",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "Future @aua_insta student",
   "Language": "Eng",
   "Length": 3,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 107,
   "Comments": 10,
   "Followers": 1023
 },
 {
   "ID": 53,
   "IG username": "shahanehh",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "I swear she's an angel✨ #retro #aesthetic #car #retrocar #retrocars #fashion #cute #beauty #dream #dreamcar #damn #lipstick #red #pink #selenagomez #purple #clouds #slut #whore #drugs #junkie #alchohol #chanel #nails #nailsofinstagram #fashion #fw #savage #tiger #tiktok",
   "Language": "Eng",
   "Length": 5,
   "# of emojis": 1,
   "# of hashtags": 30,
   "Likes": 206,
   "Comments": 25,
   "Followers": 522
 },
 {
   "ID": 54,
   "IG username": "zalyanm",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "🍩",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 190,
   "Comments": 13,
   "Followers": 638
 },
 {
   "ID": 55,
   "IG username": "_.__gev",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "😈🤙🏼",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 2,
   "# of hashtags": 0,
   "Likes": 71,
   "Comments": 4,
   "Followers": 333
 },
 {
   "ID": 56,
   "IG username": "dalita_avanessian",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "🌖🌝",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 2,
   "# of hashtags": 0,
   "Likes": 1394,
   "Comments": 28,
   "Followers": 155000
 },
 {
   "ID": 57,
   "IG username": "navarreteaz",
   "Gender": "Male",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "The @anca_wr Trip to Armenia wrapped up a series of high-level meetings with government officials as well as visits to key institutions and sites. I will post highlights throughout the next couple of days. #GoANCA #ArmDel2019\n\nAs a member of the Committee on Higher Education and Workforce Development, meeting with the President, faculty, and students of @american_university_ of Armenia resulted in very fruitful discussions. I will work to have more Arizona students to have access to study abroad opportunities that will enrich their academic experience.\nLeaders in attendance are below:\nCA Lt. Governor Eleni Kounalakis\nLA County Supervisor Kathryn Barger\nState Sen. Tony Navarrete\nState Sen. Dominick Moreno\nState Sen. Paul Boyer\nState Rep. Daneya Esgar",
   "Language": "Eng",
   "Length": 761,
   "# of emojis": 0,
   "# of hashtags": 2,
   "Likes": 135,
   "Comments": 1,
   "Followers": 1836
 },
 {
   "ID": 58,
   "IG username": "george_hasratian",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "earth, pre-corona times...",
   "Language": "Eng",
   "Length": 26,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 76,
   "Comments": 1,
   "Followers": 745
 },
 {
   "ID": 59,
   "IG username": "ohanyan.n_\n\n",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Back in the day ❤️",
   "Language": "Eng",
   "Length": 18,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 151,
   "Comments": 1,
   "Followers": 732
 },
 {
   "ID": 60,
   "IG username": "a_n_i_i_n_a",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "#missthesedays ♥️",
   "Language": "Eng",
   "Length": 17,
   "# of emojis": 1,
   "# of hashtags": 1,
   "Likes": 114,
   "Comments": 14,
   "Followers": 1185
 },
 {
   "ID": 61,
   "IG username": "olchezq",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Taking control of this kind of a moment,\nI'm locked and loaded🌸",
   "Language": "Eng",
   "Length": 64,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 120,
   "Comments": 1,
   "Followers": 504
 },
 {
   "ID": 62,
   "IG username": "gag__gyan\n",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "Тренировка 💪🏽",
   "Language": "Rus",
   "Length": 15,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 7,
   "Comments": 3,
   "Followers": 22
 },
 {
   "ID": 63,
   "IG username": "manch_menchi_yan",
   "Gender": "Female",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Smart Green took part in EPIC Demo Day and got Michael Agbabian EPIC Innovator Prize. AUA president Doctor Armen Der Kiureghian congratulated us and took wonderful photos with us. \nP.S. I am very happy that I had an opportunity to study at AUA and got to know Dr. Der Kiureghian. \n#BestPresidentEver\n#AUA #epicdemoday",
   "Language": "Eng",
   "Length": 50,
   "# of emojis": 0,
   "# of hashtags": 2,
   "Likes": 75,
   "Comments": 0,
   "Followers": 424
 },
 {
   "ID": 64,
   "IG username": "ed_217",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "It is good to learn",
   "Language": "Eng",
   "Length": 5,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 41,
   "Comments": 0,
   "Followers": 250
 },
 {
   "ID": 65,
   "IG username": "nancyhak",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no ",
   "Caption": "FLEXers❤️❤️",
   "Language": "Eng",
   "Length": 1,
   "# of emojis": 2,
   "# of hashtags": 0,
   "Likes": 105,
   "Comments": 0,
   "Followers": 758
 },
 {
   "ID": 66,
   "IG username": "sonahouse",
   "Gender": "Female",
   "Occasion": "Graduation",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Proud alumna of AUA with an MBA degree and lots of memories 🎓",
   "Language": "Eng",
   "Length": 12,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 41,
   "Comments": 4,
   "Followers": 180
 },
 {
   "ID": 67,
   "IG username": "henri.abgaryan",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Believe in yourself and all that you are. Know that there is something inside of you that is greater than any obstacle",
   "Language": "Eng",
   "Length": 22,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 46,
   "Comments": 1,
   "Followers": 238
 },
 {
   "ID": 68,
   "IG username": "si________18",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "🤍\n",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 123,
   "Comments": 12,
   "Followers": 263
 },
 {
   "ID": 69,
   "IG username": "__hripsime_._",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "Typical me💕",
   "Language": "Eng",
   "Length": 2,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 116,
   "Comments": 6,
   "Followers": 623
 },
 {
   "ID": 70,
   "IG username": "kyandaryan.t",
   "Gender": "Female",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "#aua #transformyourself #transformtheworld",
   "Language": "Eng",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 3,
   "Likes": 74,
   "Comments": 6,
   "Followers": 1223
 },
 {
   "ID": 71,
   "IG username": "adrine_kocharyan",
   "Gender": "Female",
   "Occasion": "Landscape",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "〰️",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 90,
   "Comments": 4,
   "Followers": 1617
 },
 {
   "ID": 72,
   "IG username": "aghtstep",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "Эй! А ты из какого фильма прибыл?",
   "Language": "Rus",
   "Length": 7,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 123,
   "Comments": 6,
   "Followers": 363
 },
 {
   "ID": 73,
   "IG username": "anahit__topalyan",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "20.02.2020🦇",
   "Language": "Other",
   "Length": 1,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 189,
   "Comments": 26,
   "Followers": 339
 },
 {
   "ID": 74,
   "IG username": "marimalkhasian",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Dance, boogie wonderlaaaaaand✨",
   "Language": "Eng",
   "Length": 30,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 75,
   "Comments": 7,
   "Followers": 406
 },
 {
   "ID": 75,
   "IG username": "marimalkhasian",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "🦋✨🦆🔪",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 4,
   "# of hashtags": 0,
   "Likes": 90,
   "Comments": 14,
   "Followers": 406
 },
 {
   "ID": 76,
   "IG username": "marimalkhasian",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "It’s corona time baby!\n#quarantine#spring#bored",
   "Language": "Eng",
   "Length": 22,
   "# of emojis": 0,
   "# of hashtags": 3,
   "Likes": 82,
   "Comments": 14,
   "Followers": 406
 },
 {
   "ID": 77,
   "IG username": "lil.m_822",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "yes",
   "Caption": "DISTRACTING SEATS AT AUA!!!",
   "Language": "Eng",
   "Length": 27,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 31,
   "Comments": 9,
   "Followers": 127
 },
 {
   "ID": 78,
   "IG username": "am_arakelyan_",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 53,
   "Comments": 0,
   "Followers": 259
 },
 {
   "ID": 79,
   "IG username": "am_arakelyan_",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 47,
   "Comments": 1,
   "Followers": 259
 },
 {
   "ID": 80,
   "IG username": "mashulmartirosyan\n",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 133,
   "Comments": 5,
   "Followers": 1229
 },
 {
   "ID": 81,
   "IG username": "__kristina__7\n",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "💡",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 111,
   "Comments": 24,
   "Followers": 231
 },
 {
   "ID": 82,
   "IG username": "martin_hovhannisyan_",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "yes",
   "Caption": "Շնորհակալություն իմ ուսանողուհուն",
   "Language": "Arm",
   "Length": 3,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 60,
   "Comments": 0,
   "Followers": 239
 },
 {
   "ID": 83,
   "IG username": "volunteers_league",
   "Gender": "N/A",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Happy International Volunteer’s Day Everyone!!!\nThank you for your contribution and activism in the development of volunteering in Armenia and AUA!\nLooking forward to new opportunities❤️🤗✅",
   "Language": "Eng",
   "Length": 26,
   "# of emojis": 3,
   "# of hashtags": 0,
   "Likes": 42,
   "Comments": 0,
   "Followers": 383
 },
 {
   "ID": 84,
   "IG username": "dona__every_after__",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "@caucasiansona քո գլխի տեղը պահել ենք էս նկարում 💚\nՀ.Գ. Մամի էս նկարում էնքան էլ նման չենք, բայց դե նկարները միշտ էլ խաբուսիկ են #mommy 💚\n\n#education #photographer\n#armenia #loveyou\n#friends #friendshipgoals #international\n#인스타그램 #일상 #데일리룩 #조하요 #소통 #소통해요 #팔로우미 #팔로 #팔로우 #옷스타그램 #맛팔 #셀카 #인스타그램 #스타일 #인친 #여행 #데일리룩 #데일리코",
   "Language": "Arm",
   "Length": 21,
   "# of emojis": 2,
   "# of hashtags": 9,
   "Likes": 74,
   "Comments": 0,
   "Followers": 634
 },
 {
   "ID": 85,
   "IG username": "ani.petrosyan",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Education is the most powerful weapon which we can use to change the world. #inlove #hardworker #student",
   "Language": "Eng",
   "Length": 14,
   "# of emojis": 0,
   "# of hashtags": 3,
   "Likes": 82,
   "Comments": 1,
   "Followers": 204
 },
 {
   "ID": 86,
   "IG username": "elllen.",
   "Gender": "Female",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "#halloween2019\nDevil🖤🔥 Credits to: @erika_l_02 💋🌪",
   "Language": "Eng",
   "Length": 3,
   "# of emojis": 4,
   "# of hashtags": 1,
   "Likes": 183,
   "Comments": 5,
   "Followers": 325
 },
 {
   "ID": 87,
   "IG username": "lusine_gyulnekyan",
   "Gender": "Female",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Ձեզ համար ուղղակի շենք, իսկ ինձ համար տուն է դարձել։\nԴեռ 2013-ին ես իմացա էն Ամերիկյանը, որը հիմա էլ չկա, ու էն Ամերիկյանը, որը, ցավոք շատերը չգիտեն։ Երբ 2013-ի առաջին ուսումնական օրը փնտրում էի 214w լսարանը Intro to Business-ի համար ու 11։30-ի փոխարեն 11։35 մտա լսարան, դասախոսը ներս չթողեց, նախ խնդրեց ներկայանալ, հետո հարցրեց՝ ի՞նչ սպորտաձևով ես զբաղվում։ Էդ դասախոսը մինչև էսօր իմ ֆավորիտն է, իսկ դասերի ավելի լավ սկզբի մասին հնարավոր չէր երազել։\nՀերիք չէ դասընկերներս ու ես բակալավրի առաջին սերունդն էինք, մենք բակալավրի միակ սերունդն եղանք, որ բախտ ունեցավ սովորել Bruce Boghosian-ի ու Dennis Leavens-ի «կառավարման» տարիներին։\nՄենք էնքան հաջողակ եղանք, որ մեր դասախոսը հուզվեց առաջին սեմեստրի ավարտին ու արցունքները չզսպելով դուրս եկավ լսարանից (էն ֆավորիտը էլի)։ Մենք էն սերունդն էինք, ում անուն առ անուն հիշում էին։\nՄենք ունեինք cafeteria, նույն ինքը Thomas Catering, ուր ամեն օր ժամը 10-ին թխում էին ամենահամով շոկոլադե կրեմով բուլկին, վրան էլ շաքարի փոշի 🤤: Շատ մեծ, փայտից սեղան-աթոռներով ու տան նման հարմար էր մերօրյա Aries-ը։ Հիշում եմ @suzette__ms-ի սիրած բրաունին, ու իմ չսիրած պիցցան 🤣։\nMain building-ի lab-երից մեկի փոխարեն հանդերձարանն էր՝ ձմեռային հագուստը թողնելու համար, իսկ մյուսում՝ սեղանի թենիսը։\nՄեր Ամերիկյանի լիֆտերը բարձրահարկերի լիֆտերից չէին տարբերվում, դրա համար հույսս ոտքերիս վրա էի դնում 😅\nՄեր Ամերիկյանում Orientation day-ը տոն էր, իսկ Matriculation ceremony-ն տարվա իրադարձությունը՝ դասական երաժշտության նոտաների ընկերակցությամբ։\nՈւ մենակ մեր Ամերիկյանում Dennis Leavens-ից լսեցինք ամենասիրուն ու ճիշտ խոսքերը, որ կյանքում չենք մոռանա.«Ձեր կրթությունը ձեր մատնահետքերի նման է՝ մենակ ձեզ է պատկանում» ♥️\n#americanuniversityofarmenia #alumni #classof17",
   "Language": "Arm",
   "Length": 243,
   "# of emojis": 3,
   "# of hashtags": 3,
   "Likes": 75,
   "Comments": 21,
   "Followers": 286
 },
 {
   "ID": 88,
   "IG username": "a__mary",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Hey 👋",
   "Language": "Eng",
   "Length": 1,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 92,
   "Comments": 4,
   "Followers": 352
 },
 {
   "ID": 89,
   "IG username": "tkaramyan",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 41,
   "Comments": 2,
   "Followers": 191
 },
 {
   "ID": 90,
   "IG username": "h____gevorgyan",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "The pic is taken by a genius who didn’t want to be tagged",
   "Language": "Eng",
   "Length": 13,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 113,
   "Comments": 2,
   "Followers": 702
 },
 {
   "ID": 91,
   "IG username": "rubenmalayan",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no ",
   "Caption": "Biggest dog I ever met",
   "Language": "Eng",
   "Length": 5,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 532,
   "Comments": 13,
   "Followers": 3838
 },
 {
   "ID": 92,
   "IG username": "elizabethsyan",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "•••🖤",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 2,
   "# of hashtags": 0,
   "Likes": 255,
   "Comments": 30,
   "Followers": 455
 },
 {
   "ID": 93,
   "IG username": "albertcorporations",
   "Gender": "Male",
   "Occasion": "Event",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "Unforgettable day with great people. Every story of every laureate was filled with emotion and pain that touches your heart. Words are not enough to describe... #auroraprize #auroraforum2019 #americanuniversityofarmenia #stopafringenocide",
   "Language": "Eng",
   "Length": 26,
   "# of emojis": 0,
   "# of hashtags": 4,
   "Likes": 47,
   "Comments": 2,
   "Followers": 394
 },
 {
   "ID": 94,
   "IG username": "hayk_06",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "✌️✌️",
   "Language": "Other",
   "Length": 0,
   "# of emojis": 2,
   "# of hashtags": 0,
   "Likes": 60,
   "Comments": 0,
   "Followers": 215
 },
 {
   "ID": 95,
   "IG username": "tikgh23",
   "Gender": "Male",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Isn't it funny how day by day nothing changes, but when you look back, everything's different?\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n\n#aua #squad #2019 #yerevan #armenia #friends #friendship #fall #almamater",
   "Language": "Eng",
   "Length": 16,
   "# of emojis": 0,
   "# of hashtags": 9,
   "Likes": 70,
   "Comments": 0,
   "Followers": 261
 },
 {
   "ID": 96,
   "IG username": "aspram__",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "S",
   "Study Flex": "no",
   "Caption": "Final year, loads of work...",
   "Language": "Eng",
   "Length": 5,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 222,
   "Comments": 8,
   "Followers": 575
 },
 {
   "ID": 97,
   "IG username": "apohagop",
   "Gender": "Male",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "\"Falling Down\" ..",
   "Language": "Eng",
   "Length": 2,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 66,
   "Comments": 5,
   "Followers": 320
 },
 {
   "ID": 98,
   "IG username": "_ditul_",
   "Gender": "Female",
   "Occasion": "Event",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "With Vache Gabrielyan(Dean of the Manoogian Simone College of Business and Economics) 😊",
   "Language": "Eng",
   "Length": 13,
   "# of emojis": 1,
   "# of hashtags": 0,
   "Likes": 152,
   "Comments": 2,
   "Followers": 2436
 },
 {
   "ID": 99,
   "IG username": "___.euphoria.__\n\n",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Why is it that the beautiful things are entwined more deeply with death than with life?",
   "Language": "Eng",
   "Length": 16,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 68,
   "Comments": 2,
   "Followers": 799
 },
 {
   "ID": 100,
   "IG username": "__ellada_",
   "Gender": "Female",
   "Occasion": "Lifestyle",
   "Type": "T",
   "Study Flex": "no",
   "Caption": "Calmness is a superpower",
   "Language": "Eng",
   "Length": 4,
   "# of emojis": 0,
   "# of hashtags": 0,
   "Likes": 225,
   "Comments": 10,
   "Followers": 996
 }
] 